version: "3.1"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./databasedata:/data/db

  api:
    image: node:18
    volumes:
      - ./node_modules:/node_modules
      - ./api:/api
      - ./shared:/shared
      - ./tsconfig.json:/tsconfig.json
      - ./package.json:/package.json
    ports:
      - "3001:3000"
    working_dir: /
    command: yarn run ts-node-dev --project api/tsconfig.json -r tsconfig-paths/register api/index.ts
    env_file: .env.development

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
